---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - privateca-issuer.github.com
  resources:
  - caissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - privateca-issuer.github.com
  resources:
  - caissuers/finalizers
  verbs:
  - update
- apiGroups:
  - privateca-issuer.github.com
  resources:
  - caissuers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - privateca-issuer.github.com
  resources:
  - clustercaissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - privateca-issuer.github.com
  resources:
  - clustercaissuers/finalizers
  verbs:
  - update
- apiGroups:
  - privateca-issuer.github.com
  resources:
  - clustercaissuers/status
  verbs:
  - get
  - patch
  - update
