apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controllers-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: privateca-issuer
    app.kubernetes.io/part-of: privateca-issuer
    app.kubernetes.io/managed-by: kustomize
  name: controllers-manager
  namespace: system
