apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: heliannuuthus-caissuer-certificate
  namespace: cert-manager
spec:
  commonName: certificate-by-issuer.example.com
  secretName: certificate-by-heliannuuthus-caissuer
  issuerRef:
    name: heliannuuthus-caissuer-sample
    group: privateca-issuer.github.com
    kind: SelfSignedIssuer
