apiVersion: privateca-issuer.github.com/v1alpha1
kind: SelfSignedIssuer
metadata:
  name: heliannuuthus-caissuer-sample
  namespace: cert-manager
spec:
  CASecretName: heliannuuthus-caissuer-credentials
